spring.application.name=medicheck_backend
server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/medicheck
spring.datasource.username=root
spring.datasource.password=Pmehta@123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
jwt.secret=105604480db86a6a5da69e7ef7a9a59c
file.upload-dir=uploads/