spring.application.name=medicheck_backend
server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/medicheck
spring.datasource.username=root
spring.datasource.password=Pmehta@123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
jwt.secret=105604480db86a6a5da69e7ef7a9a59c
google.client-id=$795196955520-7045fhj5ou53l71p6ee8tpbql4niend9.apps.googleusercontent.com
ocr.cloud.google.api-key=$AIzaSyDxGrwj1IbLGDJepiuhbf1y0Jcp1VAnjcs
ocr.cloud.google.min-local-score=185
ocr.mock.enabled=false
file.upload-dir=uploads/